version: '3'
services:
    app:
        build:
            context: docker/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - '.:/var/www/html'
        networks:
            - dictli
        depends_on:
            - pgsql
    pgsql:
        image: 'postgres:14'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'dictli-pgsql:/var/lib/postgresql/data'
        networks:
            - dictli
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
    nginx:
        image: 'nginx:stable-alpine'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
            - './docker/nginx:/etc/nginx/conf.d'
        networks:
            - dictli
        depends_on:
            - app
networks:
    dictli:
        driver: bridge
volumes:
    dictli-pgsql:
        driver: local
